title: 墨韵·闲章
description: 技术随笔
author: 樱漫星河
email: your-email@qq.com
github_username: yingmanxinghe
twitter_username: your-twitter

baseurl: ""  # 如果项目名不是用户名.github.io，则需要写 '/repo名'
url: "https://yingmanxinghe.github.io"

# 主题设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 分页设置（每页文章数）
paginate: 5
paginate_path: "/page/:num/"
plugins:
  - jekyll-paginate
# 侧边栏分类（可选）
categories_list: ["前端", "后端", "AI", "生活"]

# 构建选项
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor